apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-rails-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: amaratasia/kubernetes-rails-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_URL
          value: redis://redis