apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubernetes-rails-example-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 1