apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidekiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidekiq
  template:
    metadata:
      labels:
        app: sidekiq
    spec:
      containers:
      - name: sidekiq
        image: amaratasia/kubernetes-rails-example:latest
        lifecycle:
          preStop:
            exec:
              command: 
                - "sidekiqctl" 
                - "stop"
                - "/tmp/sidekiq.pid"
                - "120"
        command: ["sidekiq"]
        imagePullPolicy: Never
        env:
        - name: REDIS_URL
          value: redis://redis